OBJECTS = mss20141515.o
SRCS = mss20141515.cpp

CC = g++
CFLAGS = -g -c

TARGET = mss20141515

$(TARGET) : $(OBJECTS)
	      $(CC) -o $(TARGET) $(OBJECTS)
clean :
	rm -rf $(OBJECTS) $(TARGET)

main.o : mss20141515.cpp
